In [3]:
from robot_model_calibration.dh_model import RobotDHModel

In [5]:
import numpy as np
A = np.array([[1,2],[3,4]])
np.dot(A,A)

array([[ 7, 10],
       [15, 22]])

In [6]:
A @ A

array([[ 7, 10],
       [15, 22]])

In [7]:
pos = [1,2,3,4]
pos[:3]

[1, 2, 3]

In [8]:
type(pos)

list

In [17]:
b = np.array([[[10,11,12],[13,14,15],[16,17,18]],[[19,20,21],[22,23,24],[25,26,27]]])

In [12]:
b[1][1][0]
b[1][1] = [100,101,102]

In [18]:
len(b)

2

In [19]:
c = [1,2,3]
d = np.array(c)

In [20]:
c

[1, 2, 3]

In [21]:
d

array([1, 2, 3])

In [22]:
type(c)

list

In [23]:
type(d)

numpy.ndarray

In [24]:
x = [[[10,11,12],[13,14,15],[16,17,18]],[[19,20,21],[22,23,24],[25,26,27]]]
y = np.array(x)

In [25]:
y

array([[[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [26]:
x

[[[10, 11, 12], [13, 14, 15], [16, 17, 18]],
 [[19, 20, 21], [22, 23, 24], [25, 26, 27]]]

In [27]:
len(y[0])

3

In [28]:
len(y[0][0])

3

In [29]:
v = np.array([1,2])
np.linalg.norm(v)

2.23606797749979

In [30]:
np.sqrt(5)

2.23606797749979

list

matrix([[1, 2, 3, 4],
        [5, 6, 7, 8]])

In [40]:
type(c)

numpy.matrix

In [45]:
d = [1,2,3]
np.matrix(d)

matrix([[1, 2, 3]])

In [46]:
d

[1, 2, 3]

In [59]:
a = [1,2,3,4]
b = [5,6,7,8]
x = [a,b]
for i in range(len(x)):
    x[i].append(1)
x

[[1, 2, 3, 4, 1], [5, 6, 7, 8, 1]]

In [61]:
c = np.matrix(x)

In [62]:
c

matrix([[1, 2, 3, 4, 1],
        [5, 6, 7, 8, 1]])

In [63]:
c[1:]

matrix([[5, 6, 7, 8, 1]])

In [64]:
c[:1]

matrix([[1, 2, 3, 4, 1]])

In [65]:
c[1,1]

6

In [69]:
c[1][:]

matrix([[5, 6, 7, 8, 1]])

In [70]:
c

matrix([[1, 2, 3, 4, 1],
        [5, 6, 7, 8, 1]])

In [73]:
c[:,1].shape

(2, 1)

In [2]:
import numpy as np
theta = [0,-np.pi/2,0,0,0,0]
d = [430,0,0,699.0476,0,115]
a = [164.8701,549.6765,212.9389,0,0,0]
alpha = [-np.pi/2,0,-np.pi/2,np.pi/2,-np.pi/2,0]
beta = 0
theta1 = theta + [-8.3904,3.8788,-10.9276,-5.3444,63.3274,6.9619]

In [3]:
tehta1

NameError: name 'tehta1' is not defined

In [4]:
theta1

[0,
 -1.5707963267948966,
 0,
 0,
 0,
 0,
 -8.3904,
 3.8788,
 -10.9276,
 -5.3444,
 63.3274,
 6.9619]

In [5]:
theta1 = [i+j for i,j in zip(theta1,theta)]

In [6]:
theta1

[0, -3.141592653589793, 0, 0, 0, 0]

In [12]:
def RotX(c):
    return np.array([
    [1, 0, 0, 0], 
    [0, np.cos(c), -np.sin(c), 0],
    [0, np.sin(c),np.cos(c), 0], 
    [0, 0, 0, 1]
    ])

def RotY(b):
    return np.array([
    [np.cos(b), 0, np.sin(b), 0], 
    [0, 1, 0, 0],
    [-np.sin(b), 0,np.cos(b), 0], 
    [0, 0, 0, 1]
    ])
    
def RotZ(a):
    return np.array([
    [np.cos(a), -np.sin(a), 0, 0], 
    [np.sin(a), np.cos(a), 0, 0],
    [0, 0, 1, 0], 
    [0, 0, 0, 1]
    ])

In [39]:
from scipy.spatial.transform import Rotation

rotation_matrix = (RotZ(np.pi/6) @ RotY(35.16/180*np.pi))[:3,:3]
r = Rotation.from_matrix(rotation_matrix)
angles = r.as_euler('zyx',degrees=True)
angles 


array([ 35.22966776,  29.91474791, -19.40168719])

array([[ 0.16153455,  0.08118512,  0.98352202],
       [ 0.09326202,  0.99089436, -0.09711111],
       [-0.9824504 ,  0.10741205,  0.15249219]])

In [41]:
import math
# Checks if a matrix is a valid rotation matrix.
def isRotationMatrix(R) :
    Rt = np.transpose(R)
    shouldBeIdentity = np.dot(Rt, R)
    I = np.identity(3, dtype = R.dtype)
    n = np.linalg.norm(I - shouldBeIdentity)
    return n < 1e-6
# zyx
def RotationMatrix2EulerAngles(R) :
 
    assert(isRotationMatrix(R))
     
    sy = math.sqrt(R[0,0] * R[0,0] +  R[1,0] * R[1,0])
     
    singular = sy < 1e-6
 
    if  not singular :
        x = math.atan2(R[2,1] , R[2,2])
        y = math.atan2(-R[2,0], sy)
        z = math.atan2(R[1,0], R[0,0])
    else :
        x = math.atan2(-R[1,2], R[1,1])
        y = math.atan2(-R[2,0], sy)
        z = 0
 
    return np.array([x, y, z])

In [43]:
rotation_matrix = (RotZ(30/180*np.pi) @ RotY(79.25/180*np.pi) @ RotX(35.16/180*np.pi))[:3,:3]
RotationMatrix2EulerAngles(rotation_matrix) * 180/np.pi

array([35.16, 79.25, 30.  ])

In [36]:
rotation_matrix

array([[ 0.70801658, -0.5       ,  0.49871086],
       [ 0.40877356,  0.8660254 ,  0.28793085],
       [-0.5758617 ,  0.        ,  0.81754712]])

In [ ]:
from robot_model_calibration import tcp_calibration

In [2]:
theta_rad = [
        [-8.3904,3.8788,-10.9276,-5.3444,63.3274,6.9619],
        [7.4676,14.2118,-2.1832,4.6619,71.8547,20.8935],
        [17.0466,-4.0912,-14.6422,14.4479,78.4667,5.6805],
        [34.9356,0.9188,-7.6252,18.5939,82.0907,1.8525]
        ]


TypeError: unsupported operand type(s) for @: 'list' and 'int'

In [4]:
import numpy as np
a = np.array([1,2,3])
b = np.array([4,2,3])
a+b

array([5, 4, 6])

In [9]:
a = [1,2,3]
b = [4,2,3]
a + b
a

[1, 2, 3]

In [10]:
[a,b]

[[1, 2, 3], [4, 2, 3]]

In [8]:
a

[1, 2, 3, [4, 2, 3], [4, 2, 3]]

In [11]:
def isRotationMatrix(R) :
    R = np.matrix(R)
    Rt = np.transpose(R)
    shouldBeIdentity = np.dot(Rt, R)
    I = np.identity(3, dtype = R.dtype)
    n = np.linalg.norm(I - shouldBeIdentity)
    print(n)
    return n < 1e-6

In [22]:
from robot_model_calibration import dh_model
# dh 参数
theta0 = [0,-np.pi/2,0,0,0,np.pi]
d = [430,0,0,699.0476,0,115]
a = [164.8701,549.6765,212.9389,0,0,0]
alpha = [-np.pi/2,0,-np.pi/2,np.pi/2,-np.pi/2,0]
beta = 0


theta = [
        [-8.3904,3.8788,-10.9276,-5.3444,63.3274,6.9619],
        [7.4676,14.2118,-2.1832,4.6619,71.8547,20.8935],
        [17.0466,-4.0912,-14.6422,14.4479,78.4667,5.6805],
        [34.9356,0.9188,-7.6252,18.5939,82.0907,1.8525]
        ]

for i in range(len(theta)):
    theta[i] = [item * np.pi/180 for item in theta[i]]
for i in range(len(theta)):
    theta[i] = [x+y for x,y in zip(theta[i],theta0)]

pos = []
rot = []
for i in range(len(theta)):
    pos.append(dh_model.RobotDHModel(theta[i],d,a,alpha,beta))
    rot.append(pos[i].GetFCS()[:3,:3])



In [25]:
for i in range(len(rot)):
    a = isRotationMatrix(rot[i])
    print(a)

5.632010918916975e-16
True
2.3448518591720504e-16
True
5.715915496698613e-16
True
5.096219148640579e-16
True


In [15]:
print(type(pos[0].GetFCS()))

<class 'numpy.matrix'>


In [20]:
a = np.array(pos[0].GetFCS()[:3,:3])

In [21]:
a

array([[-0.80408848,  0.25594058,  0.53659682],
       [ 0.19863635,  0.96637687, -0.16327689],
       [-0.56034393, -0.02470143, -0.82789161]])

In [18]:
a.T

array([[-8.04088476e-01,  1.98636348e-01, -5.60343934e-01,
         0.00000000e+00],
       [ 2.55940578e-01,  9.66376872e-01, -2.47014304e-02,
         0.00000000e+00],
       [ 5.36596816e-01, -1.63276886e-01, -8.27891608e-01,
         0.00000000e+00],
       [ 9.22087251e+02, -1.45679205e+02,  1.18032277e+03,
         1.00000000e+00]])

In [19]:
a.shape

(4, 4)

In [59]:
a = [[1,2,3],[4,5,6]]
b = [[0,1,2],[3,4,5]]
c = [1,2,3]
d = [4,5,6]
e = zip(c,d)

In [61]:
print(e)

In [29]:
res = []
for i in range(len(a)):
    res.append([i - j for i,j in zip(a[i],b[i])])
print(res)

[[1, 1, 1], [1, 1, 1]]


In [40]:
dist = [[[922.0872514177624, -145.67920490063784, 1180.322766021751]], [[1030.247152058211, 143.99984025046393, 911.4439343587217]], [[733.7601785325046, 254.3906964937899, 1308.4940431748996]], [[693.5762331590286, 528.7899890189292, 1167.3499994529739]]]
dist

[[[922.0872514177624, -145.67920490063784, 1180.322766021751]],
 [[1030.247152058211, 143.99984025046393, 911.4439343587217]],
 [[733.7601785325046, 254.3906964937899, 1308.4940431748996]],
 [[693.5762331590286, 528.7899890189292, 1167.3499994529739]]]

In [41]:
dist = dist[:4]
dist

[[[922.0872514177624, -145.67920490063784, 1180.322766021751]],
 [[1030.247152058211, 143.99984025046393, 911.4439343587217]],
 [[733.7601785325046, 254.3906964937899, 1308.4940431748996]],
 [[693.5762331590286, 528.7899890189292, 1167.3499994529739]]]

In [42]:
new_dist = []
for i in range(len(dist)):
    new_dist.append(dist[i][0])

In [43]:
new_dist

[[922.0872514177624, -145.67920490063784, 1180.322766021751],
 [1030.247152058211, 143.99984025046393, 911.4439343587217],
 [733.7601785325046, 254.3906964937899, 1308.4940431748996],
 [693.5762331590286, 528.7899890189292, 1167.3499994529739]]

In [52]:
a

[[1, 2, 3],
 [4, 5, 6],
 [[0, 1, 2], [3, 4, 5]],
 [[0, 1, 2], [3, 4, 5]],
 [0, 1, 2],
 [3, 4, 5]]

In [48]:
c = a.extend(b)

In [49]:
print(c)

None


In [62]:
import math

# Define a class for a 2D point
class Point:
    def __init__(self, x, y):
        self.x = x
        self.y = y
    
    def __str__(self):
        return f"({self.x}, {self.y})" # return a formated string
    
    def distance(self, other):
        return math.sqrt((self.x - other.x)**2 + (self.y - other.y)**2)

# Define a subclass for a colored point
class ColoredPoint(Point):
    def __init__(self, x, y, color):
        super().__init__(x, y)
        self.color = color
    
    def __str__(self):
        return f"({self.x}, {self.y}, {self.color})"
    
    def darken(self):
        if self.color == "red":
            self.color = "maroon"
        elif self.color == "green":
            self.color = "forest green"
        elif self.color == "blue":
            self.color = "navy"

# Define a class for a rectangle
class Rectangle:
    def __init__(self, top_left, width, height):
        self.top_left = top_left
        self.width = width
        self.height = height
    
    def __str__(self):
        return f"Rectangle with top left corner at {self.top_left} and dimensions {self.width} x {self.height}"
    
    def area(self):
        return self.width * self.height
    
    def perimeter(self):
        return 2 * (self.width + self.height)

# Define a subclass for a colored rectangle
class ColoredRectangle(Rectangle):
    def __init__(self, top_left, width, height, color):
        super().__init__(top_left, width, height)
        self.color = color
    
    def __str__(self):
        return f"Colored rectangle with top left corner at {self.top_left}, dimensions {self.width} x {self.height}, and color {self.color}"
    
    def darken(self):
        if self.color == "red":
            self.color = "maroon"
        elif self.color == "green":
            self.color = "forest green"
        elif self.color == "blue":
            self.color = "navy"

# Create some points
p1 = Point(0, 0)
p2 = Point(3, 4)
print(p1.distance(p2))  # should print 5.0
print(p1)  # should print (0, 0)

# Create some colored points
cp1 = ColoredPoint(1, 1, "red")
cp2 = ColoredPoint(2, 2, "green")
print(cp1)  # should print (1, 1, red)
print(cp2)  # should print (2, 2, green)
cp1.darken()
cp2.darken()
print(cp1)  # should print (1, 1, maroon)
print(cp2)  # should print (2, 2, forest green)

# Create some rectangles
r1 = Rectangle(Point(0, 0), 2, 3)
r2 = Rectangle(Point(1, 1), 4, 5)
print(r1.area())  # should print 6
print(r2.perimeter())  # should print 18
print(r1)  # should print Rectangle with top left corner at (0, 0) and dimensions 2 x 3

# Create some colored rectangles
cr1 = ColoredRectangle(Point(0, 0), 2, 3, "red")
cr2 = ColoredRectangle(Point(1, 1), 4, 5, "green")
print(cr1.area())  # should print 6
print(cr2.perimeter())  # should print 18
print(cr1)  # should print Colored rectangle with top left corner at (0, 0), dimensions 2 x 3, and color red
print(cr2)  # should print Colored rectangle with top left corner at (1, 1), dimensions 4 x 5, and color green
cr1.darken()
cr2.darken()
print(cr1)  # should print Colored rectangle with top left corner at (0, 0), dimensions 2 x 3, and color maroon
print(cr2)  # should print Colored rectangle with top left corner at (1, 1), dimensions 4 x 5, and color forest green



5.0
(0, 0)
(1, 1, red)
(2, 2, green)
(1, 1, maroon)
(2, 2, forest green)
6
18
Rectangle with top left corner at (0, 0) and dimensions 2 x 3
6
18
Colored rectangle with top left corner at (0, 0), dimensions 2 x 3, and color red
Colored rectangle with top left corner at (1, 1), dimensions 4 x 5, and color green
Colored rectangle with top left corner at (0, 0), dimensions 2 x 3, and color maroon
Colored rectangle with top left corner at (1, 1), dimensions 4 x 5, and color forest green


In [64]:
class Animal:
    def __init__(self, name):
        self.name = name

    def speak(self):
        raise NotImplementedError("Subclass must implement abstract method")

class Cat(Animal):
    def __init__(self, name, color):
        super().__init__(name)
        self.color = color

    def speak(self):
        return "Meow"

c = Cat("Fluffy", "gray")
print(c.name)  # should print "Fluffy"
print(c.color)  # should print "gray"
print(c.speak())  # should print "Meow"
a = Animal('Doggy')
a.speak()

Fluffy
gray
Meow


NotImplementedError: Subclass must implement abstract method

In [65]:
import numpy as np

# Define the known distances between points in the robot's tool coordinate system
d1 = 10.0  # distance between points 1 and 2
d2 = 5.0  # distance between points 2 and 3
d3 = 8.0  # distance between points 1 and 3

# Define the measured distances between the same points in the robot's current coordinate system
measured_d1 = 10.2
measured_d2 = 4.8
measured_d3 = 7.9

# Define the initial guess for the transformation matrix
# This matrix represents a translation and rotation of the tool coordinate system
# relative to the robot's current coordinate system
# You can start with an identity matrix if you're not sure
T_guess = np.eye(4)

# Define the target distances and measured distances as arrays
d_target = np.array([d1, d2, d3])
d_measured = np.array([measured_d1, measured_d2, measured_d3])

# Define a function to calculate the error between the target and measured distances
def error(T, d_target, d_measured):
    # Transform the target distances to the current coordinate system using the current transformation matrix
    d_transformed = np.sqrt(np.sum((np.dot(T, np.array([[0, d_target[0], d_target[1], 1]]).T) - np.array([[0, d_measured[0], d_measured[1], 1]]).T)**2, axis=0))[:2]
    # Return the difference between the transformed distances and the measured distances
    return d_transformed - d_measured

# Define a function to calculate the Jacobian matrix for the error function
def jacobian(T, d_target, d_measured):
    # Calculate the partial derivatives of the error function with respect to each element of the transformation matrix
    delta = 1e-6
    J = np.zeros((len(d_target), 6))
    for i in range(6):
        T_delta = T.copy()
        T_delta[i//4,i%4] += delta
        e_delta = error(T_delta, d_target, d_measured)
        J[:,i] = (e_delta - error(T, d_target, d_measured))/delta
    return J

# Define a function to perform the calibration using the Levenberg-Marquardt algorithm
def calibrate(T_guess, d_target, d_measured, max_iter=100, tol=1e-6):
    T = T_guess.copy()
    nu = 2.0
    mu = 1e-3
    for i in range(max_iter):
        e = error(T, d_target, d_measured)
        J = jacobian(T, d_target, d_measured)
        JtJ = np.dot(J.T, J)
        Jte = np.dot(J.T, e)
        H = JtJ + mu * np.diag(np.diag(JtJ))
        try:
            delta = np.linalg.solve(H, -Jte)
        except np.linalg.LinAlgError:
            break
        T_new = np.dot(np.dot(np.linalg.inv(np.dot(np.dot(J.T, J) + mu*np.eye(6), J.T)), JtJ), T - delta)
        e_new = error(T_new, d_target, d_measured)
        if np.sqrt(np.sum(e_new**2)) < tol:
            T = T_new
        if np.sqrt(np.sum(e_new**2)) < np.sqrt(np.sum(e**2)):
            mu /= nu
            T = T_new
        else:
            mu *= nu
        if np.linalg.norm(delta) < tol:
            break
    return T

# Call the calibration function and print the resulting transformation matrix
T_calibrated = calibrate(T_guess, d_target, d_measured)
print("Calibrated transformation matrix:")
print(T_calibrated)



Calibrated transformation matrix:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [67]:
import os
print(FileNotFoundError(os.errno.ENOENT, os.strerror(os.errno.ENOENT), 'foobar'))

AttributeError: module 'os' has no attribute 'errno'